# Generated by Django 2.2.16 on 2022-05-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220518_2203'),
        ('users', '0004_auto_20220518_2136'),
    ]

    operations = [
    ]
