# Generated by Django 2.2.16 on 2022-05-19 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220518_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Оценка не может быть меньше 1.'), django.core.validators.MaxValueValidator(10, 'Оценка не может быть больше 10.')], verbose_name='Оценка'),
        ),
    ]
